In [1]:
print('fit a model with', 11, 'variables')


fit a model with 11 variables


In [3]:
3 + 5

8

In [4]:
"hello" + " " + "world"

'hello world'

In [5]:
x = [3, 4, 5]
x

[3, 4, 5]

In [6]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

In [8]:
import numpy as np

In [9]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [10]:
x + y

array([ 7, 13, 12])

In [11]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [12]:
x.ndim

2

In [13]:
x.dtype

dtype('int32')

In [14]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [15]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [16]:
x.shape

(2, 2)

In [17]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [19]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [20]:
x_reshape[0, 0] 

1

In [21]:
x_reshape[1, 2] 

6

In [22]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [23]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [24]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [25]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [26]:
x**2

array([25,  4,  9, 16, 25, 36])

In [27]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [28]:
x = np.random.normal(size=50)
x

array([-0.01604703,  0.59850788, -0.3460803 ,  0.69799666,  0.68651173,
        2.1548434 ,  0.63561912,  0.21309648, -1.43818954, -0.13327378,
       -0.24003836, -0.18435837,  0.50345532, -0.41594796,  0.19807511,
        1.31047493, -0.75902955,  0.20903518,  0.33853307,  0.84643977,
       -0.87127982,  0.32698552,  1.62361255, -0.87221663, -0.33534052,
       -1.06888547, -0.39480531, -0.40536609,  0.79216199, -1.05034706,
       -0.45648122,  0.73748613, -0.00503552, -0.81783294, -1.31113075,
        0.64935651,  0.22484012,  0.26371063,  0.98057422,  0.41255476,
        0.48133116, -1.96173872,  1.29253964,  0.72352363,  0.82357129,
       -1.45544298,  0.77409189, -0.10906974,  0.76455964,  1.11124331])

In [29]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [30]:
np.corrcoef(x, y)

array([[1.        , 0.68374697],
       [0.68374697, 1.        ]])

In [31]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2)) 

[-3.66007828  3.6358143 ]
[6.00533725 3.20066168]


In [32]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2)) 

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [33]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [34]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [35]:
np.sqrt(np.var(y)), np.std(y)

(1.6505576756498128, 1.6505576756498128)

In [36]:
X = rng.standard_normal((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])